interval = 14

[stoploss]
stoploss_enabled = true
threshold = -0.02

[thresholds]
low = 20
high = 80
lowRsi = 30
highRsi = 70
lowStochRsi = 20
highStochRsi = 80
persistenceBuy = 6
persistenceSell = 3

[bbands]
TimePeriod = 20
NbDevUp = 2
NbDevDn = 2
minPercentage = 4

[stochRsiSettings]
optInTimePeriod = 14
optInFastK_Period = 3
optInFastD_Period = 3
optInFastD_MAType = 0

[tuStochSettings]
optInFastKPeriod = 14
optInSlowKPeriod = 1
optInSlowDPeriod = 3

[macdSettings]
optInFastPeriod = 12
optInSlowPeriod = 26
optInSignalPeriod = 9